"""Predefined responses for the workers."""


class BaseResponse(dict):
    """Base response implementation."""

    def __init__(self, **elements):
        """Initialize the response with additional keywords."""
        self.setdefault('status', getattr(self, '__status__', 'success'))
        self.setdefault('message', getattr(self, '__message__', 'Job done.'))
        self.setdefault('filename', None)
        super().__init__(**elements)


class BaseErrorResponse(BaseResponse):
    """Base error response message."""

    __status__ = 'error'
    __message__ = 'Error occured!'


class NoMimeErrResponse(BaseErrorResponse):
    """Response for no mime type detected error."""

    __message__ = 'Failed to detect mime type.'


class NoProcessorDefined(BaseErrorResponse):
    """Response for no processors found error."""

    __message__ = 'No processor module found.'


class InvalidProcessorFound(BaseErrorResponse):
    """Response for invalid implementation of processor."""

    __message__ = 'Invalid processor found.'


class NoUrlGenerated(BaseErrorResponse):
    """Response for no url generation by a processor."""

    __message__ = 'No URL generated by the processor'
